import { getSqlite } from '$lib/server/db';
import { newId } from '$lib/server/id';
import { nowIso } from '$lib/server/time';
import { dirname, joinRemote } from './paths';
import { getClientForSource, getLibrary } from './sources';
import { log } from './logs';
import { metadataTargets } from './naming';
import { getSettings } from './settings';

export async function executeRenamePlan(taskId: string, planId: string) {
	const db = getSqlite();
	const plan = db.prepare('select * from rename_plans where id = ?').get(planId) as Record<string, unknown>;
	if (!plan) throw new Error('Plan not found');
	const library = getLibrary(String(plan.library_path_id));
	const client = getClientForSource(library.sourceId);
	const rows = db.prepare('select * from rename_plan_items where plan_id = ?').all(planId) as Record<
		string,
		unknown
	>[];
	let ok = 0;
	let failed = 0;
	const metadataDone = new Set<string>();
	for (const row of rows) {
		const source = String(row.source_file_path);
		const target = String(row.target_file_path);
		try {
			if (!(await client.exists(source))) throw new Error('Source file no longer exists');
			if (!Boolean(row.overwrite) && (await client.exists(target))) throw new Error('Target file exists');
			await client.ensureDirectory(dirname(target));
			await client.moveFile(source, target, { overwrite: Boolean(row.overwrite) });
			const sidecars = JSON.parse(String(row.sidecars_json || '[]')) as string[];
			for (const sidecar of sidecars) {
				try {
					if (await client.exists(sidecar)) {
						await client.moveFile(sidecar, joinRemote(dirname(target), sidecar.split('/').at(-1) || ''), {
							overwrite: Boolean(row.overwrite)
						});
					}
				} catch (error) {
					log('warn', 'RenameExecutor', 'Sidecar move failed', { sidecar, error: String(error) });
				}
			}
			await writeMetadataOnce(client, target, library.mediaType, metadataDone);
			db.prepare("update rename_plan_items set status = 'succeeded' where id = ?").run(row.id);
			db.prepare(
				`insert into execution_records
				 (id, task_id, plan_item_id, source_path, target_path, status, context_json, created_at)
				 values (?, ?, ?, ?, ?, 'succeeded', '{}', ?)`
			).run(newId(), taskId, row.id, source, target, nowIso());
			ok += 1;
		} catch (error) {
			db.prepare("update rename_plan_items set status = 'failed' where id = ?").run(row.id);
			db.prepare(
				`insert into execution_records
				 (id, task_id, plan_item_id, source_path, target_path, status, error, context_json, created_at)
				 values (?, ?, ?, ?, ?, 'failed', ?, '{}', ?)`
			).run(newId(), taskId, row.id, source, target, String(error), nowIso());
			failed += 1;
		}
	}
	const itemIds = [...new Set(rows.map((row) => String(row.library_item_id)))];
	for (const itemId of itemIds) {
		db.prepare(
			`update library_items set status = 'organized', last_execution_summary_json = @summary,
			 updated_at = @updatedAt where id = @id and status in ('identified', 'organized')`
		).run({ id: itemId, summary: JSON.stringify({ ok, failed }), updatedAt: nowIso() });
	}
	db.prepare("update rename_plans set status = 'executed' where id = ?").run(planId);
	return failed === 0 ? 'succeeded' : ok > 0 ? 'partially_failed' : 'failed';
}

async function writeMetadataOnce(
	client: { writeTextFile(path: string, content: string, overwrite?: boolean): Promise<void> },
	targetFilePath: string,
	mediaType: 'movie' | 'tv',
	done: Set<string>
) {
	const settings = getSettings();
	if (!settings.metadataEnabled) return;
	const targets = metadataTargets(targetFilePath, mediaType);
	if (done.has(targets.nfo)) return;
	done.add(targets.nfo);
	const nfo =
		mediaType === 'movie'
			? '<movie><title>Generated by Renarr</title></movie>\n'
			: '<tvshow><title>Generated by Renarr</title></tvshow>\n';
	await client.writeTextFile(targets.nfo, nfo, settings.overwriteMetadata);
}
